site:
  build: site
  ports :
   - "80:80"
  volumes:
   - /home/ncnd/info/teamManager/www:/var/www/html/
  links:
   - database
database:
  image: mariadb
  ports:
   - "3306:3306"  
  environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=symfony
     - MYSQL_USER=symfony
     - MYSQL_PASSWORD=symfony
